name: Build Windows binary

on: push

jobs:

  windows:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install gcc-mingw-w64 autoconf automake
    - name: Build binaries
      run: |
        ./autogen.sh
        ./configure --host=x86_64-w64-mingw32
        make
    - name: Display resulting tree
      run: ls -lR .
    - name: Save binaries as build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ptm2human-win64
        path: ./ptm2human.exe

